"use client";

import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { AnimatePresence } from "framer-motion";

const roboto = Roboto({
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "300", "400", "700"],
});

// const metadata: Metadata = {
//   title: "Crossblades",
//   // description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-BR"
      className="bg-zinc-200 max-w-screen max-h-screen overflow-hidden"
    >
      <head>
        <title>Crossblades</title>
      </head>
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
